# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'audioTeste' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for audioTeste
   pod 'AudioKit', '~> 4.0'
   pod 'MusicTheory', '~> 1.1'
end
